source 'https://github.com/Banuba/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlaybackAPISample' do
  pod 'BanubaSDKServicing', '1.24.0'
  pod 'VideoEditor', '1.24.0'
  pod 'BanubaUtilities', '1.24.0'
  pod 'VEEffectsSDK', '1.24.0'
  pod 'BanubaLicenseServicingSDK', '1.24.0'
  pod 'VEPlaybackSDK', '1.24.0'

  pod 'BNBLicenseUtils', '1.24.0'

  pod "BSImagePicker"
end
